### ISSUE TITLE
View Single Order Functionality

### ISSUE THREAD

**Issue by pratsajency** [ajency/EUC#10]
https://docs.google.com/a/ajency.in/document/d/1EEF6Yc-j4sk7Un5FTZ87nWH4r1Li8Mfggq0GNNJHjxM/edit#

**Comment by pratsajency** [comment]
@elroyantao 

I am not able to access/view Single Order page

![779](https://cloud.githubusercontent.com/assets/3326712/5666054/dd25eb5c-9782-11e4-86ec-f22bc1eb6617.png)

**Comment by elroyantao** [comment]
@pratsajency added the Single order view capability for the admin user
