### ISSUE TITLE
Add Stash - Added Stash is not displayed in Single View Stash page

### ISSUE THREAD

**Issue by pratsajency** [ajency/EUC#102]
Currently the added Stash is displayed in the table of Stashes. - http://euc.uk.com/dashboard/#societies/107

Clicking on any Stash, throws error "not defined" -
http://euc.uk.com/dashboard/#societies/107/stashes/68

![5](https://cloud.githubusercontent.com/assets/3326712/5570500/75251f50-8fa8-11e4-8aa4-3e433c8b012f.png)

**Comment by pratsajency** [comment]
Still getting an error "not defined" when trying to access the Stash is View mode.

**Comment by naizy** [comment]
@pratsajency capability for societies stashes single wasnt added. done now.
