### ISSUE TITLE
Add Stash - Newly added "product attributes" are not displayed while adding/editing a Stash

### ISSUE THREAD

**Issue by pratsajency** [ajency/EUC#131]
Product Attributes WP Panel - http://euc.uk.com/wp-admin/edit-tags.php?taxonomy=pa_product_types&post_type=product
Add Stash - http://euc.uk.com/dashboard/#societies/66/stashes/add

![31](https://cloud.githubusercontent.com/assets/3326712/5592594/0a08df66-91fd-11e4-98ee-812413e6011d.png)
![30](https://cloud.githubusercontent.com/assets/3326712/5592592/0987ea6e-91fd-11e4-90dc-afd4fbd5ed15.png)

**Comment by anujkhurana** [comment]
Naizy please ignore this task for now.

**Comment by naizy** [comment]
@anujkhurana , @pratsajency these are now fetched from the woocommerce products meta plugin that supresh has implemented. I've shown pratiksha how to use it a couple of days back. so this issue is invalid now.

**Comment by pratsajency** [comment]
yes, will close it
