### ISSUE TITLE
View Stash on Frontend - The Stash images displayed on Single and List View in not clear

### ISSUE THREAD

**Issue by pratsajency** [ajency/EUC#140]
The images appear blur  on Single and List View on Stashes on Frontend

![651](https://cloud.githubusercontent.com/assets/3326712/5597166/ba2dc80e-92c3-11e4-9c48-ec5cf050e0f9.png)

Actual Image

![652](https://cloud.githubusercontent.com/assets/3326712/5597169/c04d1e9c-92c3-11e4-80cf-ff2a4d51d74a.png)

**Comment by jeromie** [comment]
fixed
