### ISSUE TITLE
View Stashes - Format the Pledges count and Stash status properly on Frontend

### ISSUE THREAD

**Issue by pratsajency** [ajency/EUC#168]
http://euc.uk.com/universities/kings-college-london/football-association-kings-college-london/

![54](https://cloud.githubusercontent.com/assets/3326712/5630648/a42ef684-95e5-11e4-9580-698d5326bd7c.png)

**Comment by anujkhurana** [comment]
This is being redone. Please ignore for now.

**Comment by jeromie** [comment]
new ui implemented
