### ISSUE TITLE
Add/Edit User: Selection of multiple organizations

### ISSUE THREAD

**Issue by naizy** [ajency/EUC#196]
A user can be an euc rep/committee member of multiple organizations so the add/edit view needs to address that.

**Comment by elroyantao** [comment]
@supreshc when saving the user i have modified the organization field to have an array 

```sh
[ {id:'6',taxonamy:'universities'} , {'id:'61',taxonamy:'schools'} ]
```
and when fetching user in need an array in organization as

```sh
[ {  display_name: "Rosaries Football Club (Goa University)"
    id: 36
    name: "Rosaries Football Club"
    parent_id: 10
    parent_name: "Goa University"
    taxonomy: "universities"
},
{  display_name: "Rosaries Football Club (Goa University)"
    id: 36
    name: "Rosaries Football Club"
    parent_id: 10
    parent_name: "Goa University"
    taxonomy: "universities"}
]
```

**Comment by jeromie** [comment]
@elroyantao list of organizations moved to right column and styles added. 
When adding new user(when no organization has been added yet), display text saying "List of organizations of user will appear here" in place of organization list OR hide title Organization.

**Comment by supreshc** [comment]
@elroyantao  made the required changes mentioned and pushed to branch feature/multiple-org-user
