### ISSUE TITLE
Add Organization: euc representative as a required field

### ISSUE THREAD

**Issue by naizy** [ajency/EUC#198]
For add society/school/corporate, we need a to select euc representative.
get users of role euc_representative for this dropdown.

An organization can have multiple euc representatives. keep an 'add another' link with a plus icon at the side of the dropdown. on click of that clone the above dropdown to create another select euc representative field below the current one.

At least one euc rep is compulsory

The key value pair sent to the add/edit api request will be euc_representative:[3,5,6]

**Comment by elroyantao** [comment]
@supreshc code is on branch issue-198

**Comment by elroyantao** [comment]
@jeromie Need styling for this
