### ISSUE TITLE
Add Organization: committee members as a optional field

### ISSUE THREAD

**Issue by naizy** [ajency/EUC#199]
For add society/school/corporate, we need a field for committee members
An organization can have multiple committee members

this will be a textbox in which user will input an email id. keep an 'add another' option at d side of this on click of which a new textbox will be created below. 

This field is optional

The key value pair sent to the add/edit api request will be 
committee_members:['comm_m1@mailinator.com','comm_m2@mailinator.com']

**Comment by elroyantao** [comment]
@supreshc code in feature/issue-198 branch
sending data as ``` committee_members:['comm_m1@mailinator.com','comm_m2@mailinator.com'] ``` on save/edit

on fetch data required in same format

**Comment by elroyantao** [comment]
@supreshc committe_members and euc_representative cannot be removed

**Comment by elroyantao** [comment]
@jeromie Need styling for this

**Comment by jeromie** [comment]
@elroyantao styles added and pushed to branch feature/issue-198
