### ISSUE TITLE
Menus - The Menus should cover the full width of the page as shown in the Design pdf

### ISSUE THREAD

**Issue by pratsajency** [ajency/EUC#210]
Refer - 
https://drive.google.com/a/ajency.in/file/d/0B1VZYXFX0g0BQTlidXplQWNKV1dXSnByMGdOT0hBODhpdkRn/view?usp=sharing

![34234](https://cloud.githubusercontent.com/assets/3326712/5698994/3191dbe4-9a42-11e4-8bf6-d64fb445d6fe.png)
![213](https://cloud.githubusercontent.com/assets/3326712/5698995/319450e0-9a42-11e4-810e-298f9c3c9981.png)

**Comment by anujkhurana** [comment]
Why is this a task? Has the client responded?

**Comment by pratsajency** [comment]
No client hasnt responded.
