### ISSUE TITLE
Social Icons - Needs to be placed on the Menu also as in the design

### ISSUE THREAD

**Issue by pratsajency** [ajency/EUC#220]
Also they should look more obvious on the Site.
Currently its very light and not easily identifiable.

![545](https://cloud.githubusercontent.com/assets/3326712/5716798/3b09f0f6-9b1b-11e4-9ad7-9b6e763bf849.png)
![323](https://cloud.githubusercontent.com/assets/3326712/5716799/3b0c7114-9b1b-11e4-803d-d8f940c0c96f.png)

**Comment by jeromie** [comment]
Placed in menu bar. Removed from header. Doesnt make sense to have them in both places when one is just below the other.
