### ISSUE TITLE
Single Stash Breadcrumb 

### ISSUE THREAD

**Issue by naizy** [ajency/EUC#233]
http://euc.uk.com/dashboard/#societies/106/stashes/116 change the breadcrumb for this page to back.

if accessed through universities->societies->stashes the breadcrumb should've been 
Dashboard > Universities > {UniversityName} > {SocietyName} > Cap A
the university name & society name with their ids are present in the organizations attribue of stash.

and if accessed directly through stashes menu item
Dashboard > Stashes > Cap A

**Comment by elroyantao** [comment]
fixed
