### ISSUE TITLE
Orders not displaying for stash

### ISSUE THREAD

**Issue by naizy** [ajency/EUC#250]
http://euc.uk.com/dashboard/#stashes/108

listing page shows 9 orders recieved for this stash

**Comment by elroyantao** [comment]
@supreshc  total_sales: getting as  when there are no orders for the stash

**Comment by supreshc** [comment]
API: wc-api/v2/orders
For fetching all orders user Get Param filter[limit]=-1
For fetching orders of single stash user GET Param  product=<product_id>
