### ISSUE TITLE
Stashes list page layout

### ISSUE THREAD

**Issue by jeromie** [ajency/EUC#252]

**Comment by jeromie** [comment]
@supreshc list of stashes page layout changed for schools and corporates. Same to be done on page for list of stashes for a society. Need separate template for university and society for this.
Pushed to branch feature/stashes-list-ui

**Comment by jeromie** [comment]
@supreshc Time field added. Currently dummy data. Correct data to be fetched.
![ed 43 corporates e u c](https://cloud.githubusercontent.com/assets/5372828/5775463/1da50870-9da0-11e4-8272-fa316d6107a0.png)

**Comment by supreshc** [comment]
@jeromie added a separate template for listing of stashes of society named society.php ,copied same page layout as for listing corporates/schools stashes ,Time field displaying correct data
Pushed to branch feature/stashes-list-ui

**Comment by jeromie** [comment]
@supreshc fetch and display the full image instead of a thumbnail (150x150) for society/corporate/school image

`<div class="org-img">
		        	<img src="<?php echo $org_thumb_img;?>" class="media-object dp org-logo">
		        </div>`

**Comment by jeromie** [comment]
@supreshc can you fetch the category and display it after the name of a stash? I'll then style it.

**Comment by supreshc** [comment]
@jeromie category displayed after stash name list and single view
