### ISSUE TITLE
Access to dashboard - Committee Member does not have access to dashboard on test site inspite of having the reqd caps

### ISSUE THREAD

**Issue by pratsajency** [ajency/EUC#315]
Refer - user4@mailinator.com / 4324fsefsefsfast5235TFTF

![987](https://cloud.githubusercontent.com/assets/3326712/6121907/85ffa432-b111-11e4-8de8-f81f0e9eac2e.png)

**Comment by naizy** [comment]
@pratsajency no capabilities were assigned to committee_member role on euctest.com. assigned them now. working fine.
