### ISSUE TITLE
Client Feedback - Logo is still old design

### ISSUE THREAD

**Issue by pratsajency** [ajency/EUC#323]
Replace with new logo placed in 
https://drive.google.com/a/ajency.in/folderview?id=0B1VZYXFX0g0BX0c2RklKS01qZDg&usp=drive_web

**Comment by pratsajency** [comment]
@jeromie 
Client has shared the logo in a pdf, kindly let me know if we need to ask for a different format. Or would you be able to use the one shared by the client?

**Comment by jeromie** [comment]
@pratsajency not required in another format. I have created a jpg from the pdf provided and replaced on site.
