### ISSUE TITLE
Footer - The logo/follow us/quick links needs to be placed and formatted as shown in the document

### ISSUE THREAD

**Issue by pratsajency** [ajency/EUC#349]
Refer "EUC Web design Feb 15 Homepage" placed here
https://drive.google.com/a/ajency.in/folderview?id=0B1VZYXFX0g0BX0c2RklKS01qZDg&usp=drive_web

**Comment by jeromie** [comment]
@pratsajency placement of links and logo done as per document, but maintained formatting as earlier
