### ISSUE TITLE
Site - Fonts and colours need to be updated

### ISSUE THREAD

**Issue by pratsajency** [ajency/EUC#355]
Fonts and colours need to be updated as in the file

refer 'EUC Web design Feb 15 Homepage.cdr' here
https://drive.google.com/a/ajency.in/folderview?id=0B1VZYXFX0g0BX0c2RklKS01qZDg&usp=drive_web

**Comment by jeromie** [comment]
@pratsajency we'll need the file in another format(AI/PSD/PDF). We can't open cdr files.

**Comment by pratsajency** [comment]
@jeromie 

Refer 'EUC Web design Feb 15 Homepage' pdf in the same folder

**Comment by jeromie** [comment]
colors changed. font used is 'Dense' which isnt a webfont so used 'Oswald' instead which is the closest I could get to the font in the design.
