### ISSUE TITLE
Add Organization - No error message displayed when same Organization name is added again, instead continues to stay in loading mode

### ISSUE THREAD

**Issue by pratsajency** [ajency/EUC#81]
Display error message "This Organization Name is already added."

![12](https://cloud.githubusercontent.com/assets/3326712/5563228/d2f231c0-8e88-11e4-92f0-157d0679230c.png)

**Comment by naizy** [comment]
@anujkhurana since they are terms the name has to be unique. even in wordpress dashboard you cannot add two terms with same name under the same parent. 

i've displayed an error message to handle this issue
