### ISSUE TITLE
View Organization - The User's names should be link to their profile page. 

### ISSUE THREAD

**Issue by pratsajency** [ajency/EUC#92]
Also on hover, the link color should change to Orange

![2](https://cloud.githubusercontent.com/assets/3326712/5564299/f2678516-8edb-11e4-83a9-0f49d1211f75.png)

**Comment by pratsajency** [comment]
This is not visible on the site.
Guess its still to be pushed.

**Comment by naizy** [comment]
![screenshot 2015-01-05 11 46 07](https://cloud.githubusercontent.com/assets/5636466/5609922/9421d6cc-94d1-11e4-9cad-a2e585a43b23.png)
